language: android
android:
   components:
   - platform-tools
   - android-23
   - build-tools-22.0.1
   - extra

jdk: oraclejdk7

notifications:
  email: false

sudo: false

before_script:
  -  openssl aes-256-cbc -K $encrypted_7e1c958561a2_key -iv $encrypted_7e1c958561a2_iv -in github.properties.enc -out github.properties -d
script:
  - ./gradlew clean build
