language: android
android:
   components:
   - tools
   - tools
   - platform-tools
   - android-23
   - build-tools-23.0.3
   - extra

jdk: oraclejdk7

notifications:
  email: false

sudo: required

script:
  - ./gradlew clean build
